{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.test",
    "module": "XmlClassOk",
    "version": "1.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "XmlClassOk-1.2.4.jar",
          "url": "XmlClassOk-1.2.4.jar",
          "size": 70658,
          "sha512": "9da09f80d1966e651a261a94cfa9951381115305be597767098cb0d73501ad17f066f69c119be783de2e1aaf9d6047ed687eaec329730a0ac6ce262881d272a8",
          "sha256": "a6890a842a58416a3f4c8be45abff3b7f03ea49a73116a46c724186f8fbbd6cc",
          "sha1": "b5423a82ebffff032a795abb6e48d0b3f377a63e",
          "md5": "76dccebd3a2501f886284cdf34c81759"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "XmlClassOk-1.2.4.jar",
          "url": "XmlClassOk-1.2.4.jar",
          "size": 70658,
          "sha512": "9da09f80d1966e651a261a94cfa9951381115305be597767098cb0d73501ad17f066f69c119be783de2e1aaf9d6047ed687eaec329730a0ac6ce262881d272a8",
          "sha256": "a6890a842a58416a3f4c8be45abff3b7f03ea49a73116a46c724186f8fbbd6cc",
          "sha1": "b5423a82ebffff032a795abb6e48d0b3f377a63e",
          "md5": "76dccebd3a2501f886284cdf34c81759"
        }
      ]
    }
  ]
}
