{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.test",
    "module": "XmlClassOk",
    "version": "1.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "XmlClassOk-1.2.4.jar",
          "url": "XmlClassOk-1.2.4.jar",
          "size": 70819,
          "sha512": "3e8304a3f11e8c1e7e3fcfd637caf26be25fa20ad3743315691c12e922edab1e745b527704f16095cf84d4d4a144f251e8d09941fe52e49746597dc83aef164c",
          "sha256": "51651ad63b33d2a9cc7c74cfce590bf4fdc94ec541e9c85fea64cb99a584aa7a",
          "sha1": "64f7b257512c634565957d371304c3f0cd06ca2b",
          "md5": "83a9500ea9d08bd7492d9127f3b9e571"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "XmlClassOk-1.2.4.jar",
          "url": "XmlClassOk-1.2.4.jar",
          "size": 70819,
          "sha512": "3e8304a3f11e8c1e7e3fcfd637caf26be25fa20ad3743315691c12e922edab1e745b527704f16095cf84d4d4a144f251e8d09941fe52e49746597dc83aef164c",
          "sha256": "51651ad63b33d2a9cc7c74cfce590bf4fdc94ec541e9c85fea64cb99a584aa7a",
          "sha1": "64f7b257512c634565957d371304c3f0cd06ca2b",
          "md5": "83a9500ea9d08bd7492d9127f3b9e571"
        }
      ]
    }
  ]
}
