{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.test",
    "module": "XmlClassOk",
    "version": "1.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "XmlClassOk-1.2.4.jar",
          "url": "XmlClassOk-1.2.4.jar",
          "size": 70819,
          "sha512": "a44322e203b906da535ab22a1c22cc6c72c24ab28e09dee7f5589da08549582c48db2d8f5bd14d468285293ee44b1f4da0d8cc1cf9e71f59ee455d0568ca4279",
          "sha256": "c0425dccf9857fa5474dbf09bfcb588162da060dd2f1cb1952b87d39f921750c",
          "sha1": "53e4fd88deb8a39bdeba24f452ec725845946717",
          "md5": "cfcde720aaa89e93448a5a5f2d8333d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "XmlClassOk-1.2.4.jar",
          "url": "XmlClassOk-1.2.4.jar",
          "size": 70819,
          "sha512": "a44322e203b906da535ab22a1c22cc6c72c24ab28e09dee7f5589da08549582c48db2d8f5bd14d468285293ee44b1f4da0d8cc1cf9e71f59ee455d0568ca4279",
          "sha256": "c0425dccf9857fa5474dbf09bfcb588162da060dd2f1cb1952b87d39f921750c",
          "sha1": "53e4fd88deb8a39bdeba24f452ec725845946717",
          "md5": "cfcde720aaa89e93448a5a5f2d8333d9"
        }
      ]
    }
  ]
}
